# Generated by Django 5.2 on 2025-05-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('ci_conductor', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioForestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('comunidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('ancho', models.FloatField()),
                ('espesor', models.FloatField()),
                ('largo', models.FloatField()),
                ('cantidad_total', models.FloatField(default=0)),
                ('volumen_total', models.FloatField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'unique_together': {('especie', 'ancho', 'espesor', 'largo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRomaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('ancho', models.FloatField(help_text='En pulgadas')),
                ('espesor', models.FloatField(help_text='En pulgadas')),
                ('largo', models.FloatField(help_text='En pies')),
                ('cantidad', models.FloatField()),
                ('volumen', models.FloatField(editable=False)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('romaneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.romaneo')),
            ],
        ),
        migrations.AddField(
            model_name='romaneo',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transporte'),
        ),
        migrations.AddField(
            model_name='romaneo',
            name='usuario_forestal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarioforestal'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('volumen', models.FloatField()),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.venta')),
            ],
        ),
    ]
